eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://39.97.110.91:8761/eureka
  instance:
    prefer-ip-address: true #使用ip注册进去

server:
  port: 10000

spring:
  application:
    name: atcrowdfunding-app
  thymeleaf:
    cache: false


# SpringCloud 远程调用使用RestTemplate
#feign:
#  httpclient:
#    connection-timeout: 10000
# 我们可以调整超时时间。
logging:
  level:
    com.atguigu: debug

#feign:
#  client:
#    config:
#      readTimeout: 5000
#      connectTimeout: 5000