eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://39.97.110.91:8761/eureka
  instance:
    prefer-ip-address: true #使用ip注册进去
    ip-address: 39.105.81.163

server:
  port: 7000

spring:
  application:
    name: atcrowdfunding-user
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.81.163:3306/atcrowdfunding?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource  #使用阿里数据源
  redis:
    host: 39.105.81.163
