eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #使用ip注册进去


server:
  port: 7000

spring:
  application:
    name: atcrowdfunding-user
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.128.130:3306/atcrowdfunding?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource  #使用阿里数据源
  redis:
    host: 192.168.128.130
